@api_node_reservas_HostAddress = http://localhost:5253
@apiKey = change-this-secret-key

GET {{api_node_reservas_HostAddress}}/api/mapeamentos
Accept: application/json
x-api-key: {{apiKey}}

###

POST {{api_node_reservas_HostAddress}}/api/processamento/criar-tabelas-kb
Accept: application/json
x-api-key: {{apiKey}}

###

POST {{api_node_reservas_HostAddress}}/api/processamento/1?limit=100
Accept: application/json
x-api-key: {{apiKey}}

###

GET {{api_node_reservas_HostAddress}}/api/reservas?limit=100
Accept: application/json
x-api-key: {{apiKey}}

###
