using api_node_reservas.Dtos;
using api_node_reservas.Models;
using Microsoft.EntityFrameworkCore;

namespace api_node_reservas.Services;

public partial class KnowledgeProcessingService
{
    /*
    ============================================================================
                               Knowledge DB saving
    ============================================================================
     This file keeps the high-level saving flow for one converted record.
     The details are split into smaller files:
     - KnowledgeProcessingService.Nodes.cs saves the Node.
     - KnowledgeProcessingService.Contexts.cs saves Context rows.
     - KnowledgeProcessingService.Arcs.cs saves Arc relation rows.
    ============================================================================
    */
    // Saves one converted record into the knowledge database.
    private async Task<SaveResult> SaveKnowledgeRecordAsync(KnowledgeRecordDto record)
    {
        DateTime now = DateTime.UtcNow;
        SaveResult result = new SaveResult();

        Node node = await FindOrCreateNodeAsync(record, result);
        FillNode(node, record, now);
        await SaveNodeChangesAsync();

        await RemoveOldContextAndArcRowsAsync(node);

        AddContexts(node, record, now, result);
        await AddContextTreeRowsAsync(node, record, now, result);
        await AddArcsAsync(node, record, now, result);
        await SaveContextAndArcChangesAsync();

        return result;
    }

    // Removes old child rows so the database matches the latest source row values.
    private async Task RemoveOldContextAndArcRowsAsync(Node node)
    {
        List<Context> oldContexts = await knowledgeDbContext.Contexts
            .Where(context => context.NodeId == node.Id
                && (context.Location != 0
                    || context.DescriptionType == null
                    || context.DescriptionType != TreeContextDescriptionType))
            .ToListAsync();
        List<Arc> oldArcs = await knowledgeDbContext.Arcs.Where(arc => arc.Source == node.Id).ToListAsync();

        knowledgeDbContext.Contexts.RemoveRange(oldContexts);
        knowledgeDbContext.Arcs.RemoveRange(oldArcs);
    }

    // Saves Node changes and gives a beginner-friendly error if SQL rejects them.
    private async Task SaveNodeChangesAsync()
    {
        try
        {
            await knowledgeDbContext.SaveChangesAsync();
        }
        catch (DbUpdateException exception)
        {
            throw new InvalidOperationException(
                "Error saving the Node to the knowledge base. Check whether the Node table accepts TypeId + Type as the identifier and whether an old unique constraint still exists on the reference field.",
                exception);
        }
    }

    // Saves Context and Arc changes and gives a beginner-friendly error if SQL rejects them.
    private async Task SaveContextAndArcChangesAsync()
    {
        try
        {
            await knowledgeDbContext.SaveChangesAsync();
        }
        catch (DbUpdateException exception)
        {
            throw new InvalidOperationException(
                "Error saving Contexts or Arcs to the knowledge base. Check whether the source, target, typeId, parent and nodeId fields accept the values generated by processing.",
                exception);
        }
    }
}
