using api_node_reservas.Dtos;
using api_node_reservas.Models;
using Microsoft.EntityFrameworkCore;

namespace api_node_reservas.Services;

public partial class KnowledgeProcessingService
{
    /*
    ============================================================================
                               Knowledge DB saving
    ============================================================================
     This part writes the converted record to the knowledge database:
     - Node: the main object.
     - Context: extra text connected to the node.
     - Arc: a relation from this node to another node.
    ============================================================================
    */
    // Saves one converted record into the knowledge database.
    private async Task<SaveResult> SaveKnowledgeRecordAsync(KnowledgeRecordDto record)
    {
        DateTime now = DateTime.UtcNow;
        SaveResult result = new();
        int typeId = ToInt(record.IdInformacao);
        string type = LimitText(record.Tipo, 30);

        // One Node is identified by TypeId + Type.
        // Example: id 1 as "Reserva" is different from id 1 as "ProdutoReservado".
        Node? node = await knowledgeDbContext.Nodes
            .FirstOrDefaultAsync(existingNode => existingNode.TypeId == typeId && existingNode.Type == type);

        if (node is null)
        {
            node = new Node
            {
                Reference = LimitText(record.Reference, 1000),
                TypeId = typeId,
                Type = type
            };

            knowledgeDbContext.Nodes.Add(node);
            result.NodeCreated = true;
        }
        else
        {
            result.NodeUpdated = true;
        }

        // Fill all Node fields before the first SaveChanges.
        FillNode(node, record, now);

        try
        {
            await knowledgeDbContext.SaveChangesAsync();
        }
        catch (DbUpdateException exception)
        {
            throw new InvalidOperationException(
                "Error saving the Node to the knowledge base. Check whether the Node table accepts TypeId + Type as the identifier and whether an old unique constraint still exists on the reference field.",
                exception);
        }

        List<Context> oldContexts = await knowledgeDbContext.Contexts.Where(context => context.NodeId == node.Id).ToListAsync();
        List<Arc> oldArcs = await knowledgeDbContext.Arcs.Where(arc => arc.Source == node.Id).ToListAsync();

        // Recreate Contexts and Arcs so they always match the latest source row values.
        knowledgeDbContext.Contexts.RemoveRange(oldContexts);
        knowledgeDbContext.Arcs.RemoveRange(oldArcs);

        AddContexts(node, record, now, result);
        await AddArcsAsync(node, record, now, result);

        try
        {
            await knowledgeDbContext.SaveChangesAsync();
        }
        catch (DbUpdateException exception)
        {
            throw new InvalidOperationException(
                "Error saving Contexts or Arcs to the knowledge base. Check whether the source, target, typeId and nodeId fields accept the values generated by processing.",
                exception);
        }

        return result;
    }

    // Creates the Context rows for one Node.
    private void AddContexts(Node node, KnowledgeRecordDto record, DateTime updateDate, SaveResult result)
    {
        // Location is the order of the context value for this Node: 1, 2, 3, ...
        int location = 1;

        foreach (string contextValue in record.Contexts)
        {
            if (string.IsNullOrWhiteSpace(contextValue))
            {
                continue;
            }

            knowledgeDbContext.Contexts.Add(new Context
            {
                NodeId = node.Id,
                Description = LimitText(contextValue, 8000),
                Location = location,
                Par1 = null,
                UpdateDate = updateDate,
                DescriptionType = null
            });

            location++;
            result.ContextsCreated++;
        }
    }

    // Creates all Arc relation rows for one Node.
    private async Task AddArcsAsync(Node node, KnowledgeRecordDto record, DateTime updateDate, SaveResult result)
    {
        // Parent values are saved as "parent" relations.
        foreach (string parent in record.Parent)
        {
            await AddArcAsync(node, "parent", parent, record.TipoE, updateDate, result);
        }

        // Custom relation mappings are saved with the relation type from mapeamentos.json.
        foreach (KnowledgeRelationDto relation in record.Relations)
        {
            await AddArcAsync(node, relation.Type, relation.TargetId, relation.TargetType, updateDate, result);
        }
    }

    // Creates one Arc row if the target Node can be found safely.
    private async Task AddArcAsync(
        Node node,
        string relationType,
        string targetIdText,
        string targetType,
        DateTime updateDate,
        SaveResult result)
    {
        if (string.IsNullOrWhiteSpace(targetIdText))
        {
            // Without a target id there is no relation to create.
            return;
        }

        int? targetNodeId = await FindTargetNodeIdAsync(targetIdText, targetType);

        if (targetNodeId is null)
        {
            // The source Node is still saved, but the relation is skipped.
            logger.LogWarning(
                "Arc target was not found or is ambiguous. Source node: {SourceNodeId}, TargetId: {TargetId}, TargetType: {TargetType}.",
                node.Id,
                targetIdText,
                targetType);

            return;
        }

        knowledgeDbContext.Arcs.Add(new Arc
        {
            Source = node.Id,
            Target = targetNodeId.Value,
            TypeId = 0,
            Type = LimitText(relationType, 50),
            UpdateDate = updateDate
        });

        result.ArcsCreated++;
    }

    // Finds the database id of the target Node used by an Arc relation.
    private async Task<int?> FindTargetNodeIdAsync(string targetIdText, string targetType)
    {
        int targetTypeId = ToInt(targetIdText);

        // If the relation tells us the target type, the lookup is exact.
        if (!string.IsNullOrWhiteSpace(targetType))
        {
            Node? targetNode = await knowledgeDbContext.Nodes.FirstOrDefaultAsync(node =>
                node.TypeId == targetTypeId && node.Type == targetType);

            return targetNode?.Id;
        }

        // Without a type, the id must match exactly one Node.
        // If it matches zero or many Nodes, the relation would be unsafe.
        List<Node> possibleTargets = await knowledgeDbContext.Nodes
            .Where(node => node.TypeId == targetTypeId)
            .Take(2)
            .ToListAsync();

        if (possibleTargets.Count == 1)
        {
            return possibleTargets[0].Id;
        }

        return null;
    }

    // Copies the DTO values into the Node model before saving.
    private static void FillNode(Node node, KnowledgeRecordDto record, DateTime updateDate)
    {
        // This method is the only place where DTO fields are copied into a Node.
        node.Reference = LimitText(record.Reference, 1000);
        node.TypeId = ToInt(record.IdInformacao);
        node.Type = LimitText(record.Tipo, 30);
        node.Description = LimitText(record.Descricao, 8000);
        node.Par1 = LimitText(record.Par1, 200);
        node.Par2 = LimitText(record.Par2, 200);
        node.Par3 = LimitText(record.Par3, 200);
        node.Par4 = LimitText(record.Par4, 200);
        node.Par5 = LimitText(record.Par5, 200);
        node.Par6 = LimitText(record.Par6, 200);
        node.Par7 = LimitText(record.Par7, 200);
        node.Link = string.Empty;
        node.Security = 0;
        node.UpdateDate = updateDate;
        node.UpdateUser = 0;
        node.DescriptionType = null;
    }
}
